### ISSUE TITLE
Able to build Mixed Framework via Command line, but cannot build in Xcode via Tulsi

### ISSUE THREAD

**Issue by tinder-maxwellelliott** [line/rules_apple_line#16]
Hello There,

First and foremost, thank you for this wonderful library I am quite excited to use it. As for my issue, I am seeing success when building a mixed framework via command line, something like this:

`bazelisk build @CocoaLumberjack//:CocoaLumberjackFramework --apple_platform_type=ios  --ios_multi_cpus=x86_64,arm64 -c opt`

Works and builds a framework zip, but when I link to `@CocoaLumberjack//:CocoaLumberjack` in my other rules I am seeing this issue:

<img width="1123" alt="Screen Shot 2020-08-20 at 11 13 44 AM" src="https://user-images.githubusercontent.com/56700854/90809398-4236fc80-e2d6-11ea-8594-c78c59777645.png">

Is this an issue around using `enable_modules` or not? I could modify these calls to use `@import Cocoalumberjack;`

I have a branch of off the [bazel examples repo that replicates this issue using Tulsi](https://github.com/tinder-maxwellelliott/examples/tree/issues_with_mixed_framework), there is a working Tulsiproject in that branch at `tutorial/ios-app/BazelExample.tulsiproj`

Thank you for any help here!

**Comment by thii** [comment]
Hi there,

Thanks for the detailed report.

First and foremost, this issue is not related to Tulsi at all. I have been able to reproduce the above error by building the example iOS app target.

```
cd tutorial
bazel build //ios-app
```

The error was because the Swift generated header expects an umbrella header at “ModuleName/ModuleName.h” in its header search paths. Internally we have a convention that all modules’ umbrella headers are at this expected location, so it works for us without having to add any addition search path. This limitation should have been documented (or fixed with a generated header map).

That said, this can be worked around by using a `genrule` target to copy the CocoaLumberjack’s umbrella header to the expected location. I was able to build your example with the following patch:

```diff
diff --git i/tutorial/ios-app/Vendor/CocoaLumberjack/BUILD w/tutorial/ios-app/Vendor/CocoaLumberjack/BUILD
index cba3d48..00d5226 100644
--- i/tutorial/ios-app/Vendor/CocoaLumberjack/BUILD
+++ w/tutorial/ios-app/Vendor/CocoaLumberjack/BUILD
@@ -1,5 +1,12 @@
 load("@rules_apple_line//apple:mixed_static_framework.bzl", "mixed_static_framework")
 
+genrule(
+    name = "CocoaLumberjack_h",
+    srcs = ["CocoaLumberjack/Supporting Files/CocoaLumberjack.h"],
+    outs = ["CocoaLumberjack/CocoaLumberjack.h"],
+    cmd = "cp '$<' $@",
+)
+
 mixed_static_framework(
     name = "CocoaLumberjack",
     srcs = glob([
@@ -11,7 +18,7 @@ mixed_static_framework(
     ], [
         "CocoaLumberjack/Supporting Files/CocoaLumberjack.h",
         "CocoaLumberjackSwift/Supporting Files/CocoaLumberjackSwift.h"
-    ]),
+    ]) + [":CocoaLumberjack_h"],
     includes = [
         "CocoaLumberjack/include"
     ], 
```

**Comment by tinder-maxwellelliott** [comment]
Circling back here before I go. So it turned out your tip did get it working again, but also Tulsi was having issues with finding headers. For some reason running the tests in Tulsi it still works, but if I run in Tulsi it fails. I have confirmed this by being able to still build from the command line and make ipa files, but Tulsi cannot build the app.
